name: CI/CD Pipeline to Automate Deployments

on:
  push:
    branches:
      - master

jobs:
  infrastructure:
    name: Manage Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform Configuration
        uses: actions/checkout@v3

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Log in to IBM Cloud
        run: ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r ${{ secrets.IBM_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          IBM_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: terraform apply -auto-approve

  build:
    name: Build and Push Docker Image to Artifactory/Nexus
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Artifactory/Nexus
        run: |
          docker login ${{ secrets.ARTIFACTORY_URL }} -u ${{ secrets.ARTIFACTORY_USERNAME }} -p ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_URL }}/my-repo/my-app:latest .
          docker push ${{ secrets.ARTIFACTORY_URL }}/my-repo/my-app:latest

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Pytest
        run: pytest tests/

  deploy:
    name: Deploy to IBM Cloud Kubernetes Service
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Log in to IBM Cloud
        run: ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r ${{ secrets.IBM_REGION }}

      - name: Configure Kubernetes Context
        run: |
          ibmcloud ks cluster-config --cluster ${{ secrets.IBM_KUBERNETES_CLUSTER }}
          export KUBECONFIG=$(ibmcloud ks cluster-config --cluster ${{ secrets.IBM_KUBERNETES_CLUSTER }} | grep export | awk '{print $2}')

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy Application with Helm
        run: |
          helm upgrade --install my-app ./helm-chart \
            --set image.repository=${{ secrets.ARTIFACTORY_URL }}/my-repo/my-app \
            --set image.tag=latest
